name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install -e .; fi
          pip install pytest ruff mypy

      - name: Lint (ruff)
        run: ruff check .

      - name: Types (mypy)
        run: mypy .
        continue-on-error: true

      - name: Tests (pytest)
        run: pytest -q
